name: Shorebird Patch
description: Create a new patch using the Shorebird CLI

branding:
  icon: package
  color: green

inputs:
  args:
    description: The arguments to pass to the Shorebird patch command
    required: false
    default: ""
  platform:
    description: The platform for which to create a patch (e.g. android, ios)
    required: true
  release-version:
    description: The release version to patch (e.g. 1.0.0+1). Use "latest" to target the release that was most recently updated.
    required: true
  working-directory:
    description: The working directory in which to run Shorebird
    required: false
    default: .

outputs:
  patch-number:
    description: The number of the patch that was created.
    value: ${{ steps.shorebird-patch.outputs.patch-number }}

runs:
  using: composite
  steps:
    - name: 🐦 Shorebird Patch
      shell: bash
      id: shorebird-patch
      working-directory: ${{ inputs.working-directory }}
      run: |
        shorebird patch ${{ inputs.platform }} --release-version ${{ inputs.release-version }} ${{ inputs.args }} | tee output.log
        GREP_MATCH=$(grep -Ei "Published Patch (.*)" output.log)
        if [[ $GREP_MATCH ]]; then
          # Strip the non-version-number characters from the line
          PATCH_NUMBER=$(echo $GREP_MATCH | sed -E 's/^.+ Published Patch (.*)\!$/\1/')
          echo "patch-number=$(echo $PATCH_NUMBER)" >> $GITHUB_OUTPUT
        else
          echo "Failed to create patch"
          exit 1
        fi
